<?php
/** @var \M2E\Core\Block\Adminhtml\ControlPanel\Widget\Database $block */
?>

<style>
    .category {
        font-size: 14px;
        color: #ea7601;
    }
    td.edit-database a {
        padding-left: 10px !important;
    }
</style>

<div class="fieldset-wrapper" id="magento_block_control_panel_database_general">
    <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
        <h4><?= $block->getWidgetTitle(); ?></h4>
    </div>
    <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">

                <?php foreach ($block->getTablesInfo() as $category => $tables) : ?>
                    <tr>
                        <td class="label category" colspan="3"><label><?= $category; ?>: </label></td>
                    </tr>

                    <?php foreach ($tables as $table => $data) : ?>
                        <tr>
                            <td class="label" style="padding-right: 10px;"><?= $table; ?></td>
                            <td class="value"><?= $data['count']; ?></td>
                            <td class="value edit-database"><a href="<?= $data['url'] ?>">Edit</a></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td class="label"></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
