<?php
/** @var \M2E\Core\Block\Adminhtml\ControlPanel\Widget\Information $block */
?>
<?php
$magentoHelper = $block->getMagentoHelper();
$module = $block->getModule();
?>

<script>
    function SetupManagementActionHandler() {
        this.askAdditionalParametersForAction = function (promptString, url, placeHolder) {
            var result = prompt(promptString);
            if (result == null) {
                return false;
            }
            url = url.replace(encodeURIComponent('#') + placeHolder + encodeURIComponent('#'), result);
            document.location = url;
        }
    }

    window.setupManagementActionHandler = new SetupManagementActionHandler();
</script>

<div class="fieldset-wrapper" id="magento_block_control_panel_info_module">
    <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
        <h4><?= $block->getWidgetTitle(); ?></h4>
    </div>
    <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label><?= __('System | Current Time'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getSystemName() . ' | ' . $block->getSystemTime(); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Magento'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= __(ucwords($magentoHelper->getEditionName()))
                        . ' (' . $magentoHelper->getVersion() . ')'; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Module [Public]'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $module->getPublicVersion(); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Module [Setup]'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $module->getSetupVersion(); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Module Environment'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getEnvironment(); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Maintenance'); ?>: </label>
                    </td>
                    <td class="value">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td>
                        <span style="<?= $block->isModuleMaintenanceMode() ? 'color: green;' : 'color: red;'; ?>">
                            <?= $block->isModuleMaintenanceMode() ? __('enabled') : __('disabled'); ?>
                        </span>
                                </td>
                                <td>
                        <span style="color: orange;">
                            &nbsp;<a href="<?= $block->getUrl('*/controlPanel_inspection/changeMaintenanceMode') ?>"
                                     onclick="return confirm('Are you sure?');">[<?= __('change'); ?>]</a>
                        </span>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Core Resource'); ?>: </label>
                    </td>
                    <td class="value">
                        <table class="form-list" cellspacing="0" cellpadding="0">
                            <tr>
                                <td>
                        <span <?php if (!$block->isSetupVersionActual()) { echo ' style="color: red;" ';} ?>>
                            <?= $module->getSchemaVersion() . ' / ' . $module->getDataVersion() ?>
                        </span>
                                </td>
                                <td>
                        <span style="color: orange;">
                            &nbsp;<a href="javascript:void(0);"
                                     onclick="return setupManagementActionHandler.askAdditionalParametersForAction('Repeat upgrade from the following version:', '<?php
                                     echo $block->getUrl(
                                         '*/controlPanel_inspection/setMagentoCoreSetupValue',
                                         ['_query' => ['version' => '#version#']]
                                     ) ?>', 'version');">[<?= __('set'); ?>]</a>
                        </span>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('PHP'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getPhpVersion(); ?>
                        <a target="_blank"
                           href="<?= $block->getUrl('*/controlPanel_inspection/phpInfo') ?>"
                           style="padding-left: 10px;">
                            <?= __('[info]'); ?>
                        </a>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Server API'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getPhpApiName(); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Memory Limit'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getMemoryLimit() . ' Mb'; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Max Execution Time'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getMaxExecutionTime() == 0
                            ? __('Unlimited')
                            : $block->getMaxExecutionTime() . ' sec'; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('MySQL'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $block->getMysqlVersion(); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('MySQL Database | Tables Prefix'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $magentoHelper->getDatabaseName() . ' | ' . $block->getDatabaseTablesPrefix(); ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
