<?php
/** @var \M2E\Core\Block\Adminhtml\ControlPanel\Widget\License $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
$domainIdentifier = $block->getLicense()->getInfo()->getDomainIdentifier();
$ipIdentifier = $block->getLicense()->getInfo()->getIpIdentifier();
$clientHelper = $block->getClientHelper();
?>
<div class="fieldset-wrapper" id="magento_block_control_panel_info_location">
    <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
        <h4><?= $block->getWidgetTitle(); ?></h4>
    </div>
    <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label><?= __('Extension Key'); ?>: </label>
                    </td>
                    <td class="value">
                        <?= $escaper->escapeHtml($block->getLicense()->getKey()); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('Domain [valid | real]'); ?>: </label>
                    </td>
                    <td class="value">
                        <span <?= $domainIdentifier->isValid() ? '' : 'style="color:red;"' ?>>
                            <?= $escaper->escapeHtml(
                                $domainIdentifier->getValidValue()
                                . ' | '
                                . $clientHelper->getDomain()); ?>
                        </span>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <label><?= __('IP [valid | real]'); ?>: </label>
                    </td>
                    <td class="value">
                        <span <?= $ipIdentifier->isValid() ? '' : 'style="color:red;"' ?>>
                            <?= $escaper->escapeHtml($ipIdentifier->getValidValue()
                                . ' | '
                                . $clientHelper->getIp()); ?>
                        </span>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
