<?php
/** @var $block \M2E\Core\Block\Adminhtml\Widget\SmartTitleInterface */
/** @var $escaper \Magento\Framework\Escaper */
?>
<?php
$titleIdHtml = ($block->getTitleId()) ? ' id="' . $escaper->escapeHtmlAttr($block->getTitleId()) . '"' : '';
$titleClass = ($block->getTitleClass()) ? ' ' . $block->getTitleClass() : '';
$dropdownClassHtml = $block->hasMore() ? ' class="smart-title-active-item"' : '';
?>
<div class="page-title-wrapper<?= $escaper->escapeHtmlAttr($titleClass) ?> smart-title-wrapper"
     data-mage-init='{"M2E_Core/js/Widget/SmartTitle":{}}'>
    <h1 class="page-title"<?= /* @noEscape */ $titleIdHtml ?>>
        <?= $escaper->escapeHtml($block->getTitlePrefix()) ?>
        <span <?= /* @noEscape */ $dropdownClassHtml ?>>
            "<?= $escaper->escapeHtml($block->getCurrentTitleItem()->getTitle()) ?>"
        </span>
    </h1>
    <?php if ($block->hasMore()) { ?>
        <span class="smart-title-dropdown-menu">
                    <?php foreach ($block->getTitleItems() as $item) { ?>
                        <a class="smart-title-dropdown-item"
                              href="<?= $escaper->escapeUrl($block->getItemUrl($item)) ?>">
                            <?= $escaper->escapeHtml($item->getTitle()); ?>
                        </a>
                    <?php } ?>
                </span>
    <?php } ?>

    <?= $block->getChildHtml() ?>
</div>
