<?php
/** @var $block \M2E\Core\Block\Adminhtml\Magento\Button\DropDown */
?>

<div <?= $block->getAttributesHtml(); ?>>
    <?php if ($block->hasSplit()): ?>
        <button <?= $block->getToggleAttributesHtml() ?> style="position: static; padding-left: 2rem;">
            <span style="position: static;
                         display: inline;
                         visibility: visible;">
                <?= $block->escapeHtml($block->getLabel()); ?>
            </span>
        </button>

        <?php if (!$block->getDisabled()): ?>
            <ul class="dropdown-menu" <?= $block->getUiId("dropdown-menu"); ?>>
                <?php foreach ($block->getOptions() as $key => $option): ?>
                    <li>
                        <span <?= $block->getOptionAttributesHtml($key, $option); ?>>
                            <?= $block->escapeHtml($option['label']); ?>
                        </span>
                        <?php if (isset($option['hint'])): ?>
                            <div class="tooltip" <?php
                            /* @escapeNotVerified */
                            echo $block->getUiId('item', $key, 'tooltip'); ?>>
                                <a href="<?= $block->escapeHtml($option['hint']['href']) ?>" class="help">
                                    <?= $block->escapeHtml($option['hint']['label']) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</div>

<script>
    require(['jquery'], function ($) {
        $('.actions-split')
            .on('click.splitDefault', '.action-default', function () {
                $(this).siblings('.dropdown-menu').find('.item-default').trigger('click');
            });
    });
</script>
