<?php
/** @var \M2E\Core\Block\Adminhtml\ControlPanel\Tab\Cron $block */
?>
<div class="entry-edit group_container_summary control_panel_cron_tab">
    <div class="control_panel_head_container">
        <h4>Run Task</h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table class="form-list" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="label">
                        <label for="task_code">Task Name: </label>
                    </td>
                    <td class="value">
                        <select id="task_code" name="task_code" >
                            <option value="">-- run all --</option>
                            <?php foreach ($block->getTasks() as $optgroup => $tasks) : ?>
                                <optgroup label="<?= $optgroup; ?>">
                                    <?php foreach ($tasks as $taskCode => $taskTitle) : ?>
                                        <option value="<?= rawurlencode($taskCode); ?>"><?= $taskTitle; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            <?php endforeach; ?>
                        </select>
                        <a class="action-default scalable add" onclick="window.open('<?= $block->getCronRunUrl(); ?>'.replace('task-plx', $('task_code').value));" href="javascript:void(0);" style="display: inline !important; margin-left: 10px;">Run</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
