<?php
/** @var \M2E\Core\Block\Adminhtml\ControlPanel\Tab\ModuleTools $block */

// @codingStandardsIgnoreFile
?>
<script>
    function SetupManagementActionHandler() {
        this.askAdditionalParametersForAction = function(promptString, url, placeHolder)
        {
            var result = prompt(promptString);
            if (result == null) {
                return false;
            }
            url = url.replace(encodeURIComponent('#') + placeHolder + encodeURIComponent('#'), result);
            document.location = url;
        }
    }
    window.setupManagementActionHandler = new SetupManagementActionHandler();
</script>
<div class="page-layout-admin-2columns-left" style="margin-top: 20px;">
    <div class="page-columns">
        <div class="main-col">
            <div id="tools_module_tabs">
            </div>
        </div>
        <div class="side-col">
            <?= $block->getChildHtml('tabs'); ?>
        </div>
    </div>
</div>
